apiVersion: v2
name: ska-tmc-dishleafnode
description: A subchart for ska-tmc-dishleafnode deployment.
type: application
version: 0.45.4
appVersion: 0.45.4
icon: https://www.skatelescope.org/wp-content/uploads/2016/07/09545_NEW_LOGO_2014.png
maintainers:
  - name: Team Sahyadri, Team Himalaya
    email: telmgt-internal@googlegroups.com
dependencies:
- name: ska-tango-base
  version: 1.0.7
  repository: https://artefact.skao.int/repository/helm-internal
  condition: ska-tango-base.enabled,global.sub-system.ska-tango-base.enabled
- name: ska-tango-util
  version: 1.0.7
  repository: https://artefact.skao.int/repository/helm-internal
