display: ":0"
xauthority: "~/.Xauthority"

enabled: true

system: SW-infrastructure
subsystem: ska-tmc-dishleafnode
telescope: SKA-mid
legacy_compatibility: true

labels:
  app: ska-tmc-dishleafnode

global:
  minikube: true
  tango_host: databaseds-tango-base-test:10000
  domain: mid-tmc
  domain_dish: mid-dish
  retry:
  - "--tries=10"
  - "--sleep=5"
  dish_devices:
    - "dishleafnode"
  dishes: ["01", "02"]

dsconfig:
  configuration_file: data/configuration.json
  timeout: 300s
  image:
      registry: artefact.skao.int
      image: ska-tango-images-tango-dsconfig
      tag: 1.5.5
      pullPolicy: IfNotPresent

itango:
  image:
    registry: artefact.skao.int
    image: ska-tango-images-tango-itango
    tag: 9.3.9
    pullPolicy: IfNotPresent

dishleafnode:
  image:
    registry: artefact.skao.int
    image: ska-tmc-dishleafnode
    tag: 0.45.4
    pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 2000m
    memory: 1000Mi
    
  requests:
    cpu: 1100m
    memory: 500Mi

deviceServers:
  dishln:
    enabled: true
    instances: ["01", "02"]
    family: "dish-manager"
    family: "leaf-node-dish"
    prefix_member : "ska"
    pointing_family : "dish-pointing"
    MaxTrackTableRetry: 3
    TrackTableRetryDuration: 0.2
    file: "data/dishleafnode.yaml"
    IsDishAbortEnabled: False
    LivelinessCheckPeriod: 1.0
    EventSubscriptionCheckPeriod: 1.0
    CommandTimeOutDefault: 30.0
    AdapterTimeOut: 2.0
    DishAvailabilityCheckTimeout: 3
    source_uris: gitlab://gitlab.com/ska-telescope/ska-telmodel-data?main#tmdata
    array_layout_path: instrument/ska1_mid/layout/mid-layout.json
    weather_station_device_names: 
      - "ska-mid/weather-monitoring/s1"
      - "ska-mid/weather-monitoring/s2"
    max_allowed_wind_speed: 13.5
    max_allowed_ops_wind_speed: 10
    max_allowed_gust_wind_speed: 20  
    max_allowed_wind_speed_difference: 4.5
    wind_speed_measurement_time_window: 1000
    gust_wind_speed_measurement_time_window: 3
    mean_wind_speed_measurement_time_window: 600
    max_allowed_ops_mean_wind_speed_measurement_time_window: 600
    max_temp_threshold: 40.0
    min_temp_threshold: -5
    time_delta: 1000.0
    temp_delta: 10.0 #inflated 
    enable_auto_stow: true
    
  dishpointingdevice:
    enabled: true
    instances: ["01", "02"]
    TrackTableUpdateRate: 50
    TrackTableEntries: 50
    PointingCalculationPeriod: 50
    TrackTableInAdvance: 7
    Elevation: 30.0
    Azimuth: 0.0
    ElevationMaxLimit: 90.0
    ElevationMinLimit: 15.0
    AzimuthMinLimit: -270.0
    AzimuthMaxLimit: 270.0
    SchedularQueuePreEntries: 3
    ProgramTrackTableSize: 50

    file: "data/dishpointingdevice.yaml"


nodeSelector: {}

affinity: {}

tolerations: []
